DROP TYPE IF EXISTS theme_cat;
CREATE TYPE theme_cat AS ENUM (
	'modern',
	'historic',
	'scifi',
	'fantasy',
	'off'
);

DROP TYPE IF EXISTS noun_cat;
CREATE TYPE noun_cat AS ENUM (
	'abstract',
	'animate',
	'container',
	'genre',
	'group',
	'location',
	'object',
	'period',
	'setting',
	'substance'
);

CREATE TABLE nouns (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	category noun_cat NOT NULL,
	singular TEXT NOT NULL,
	plural TEXT,
	prep TEXT,
	theme theme_cat
);

CREATE TABLE verbs (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	infinitive TEXT NOT NULL,
	present TEXT NOT NULL,
	past TEXT NOT NULL,
	gerund TEXT NOT NULL
);

DROP TYPE IF EXISTS adjective_cat;
CREATE TYPE adjective_cat AS ENUM (
	'adverb',
	'animate',
	'general',
	'modifier',
	'object',
	'place'
);

CREATE TABLE adjectives (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	category adjective_cat NOT NULL,
	adj TEXT NOT NULL,
	theme theme_cat
);