-- psql -U zacharialutz -d wordbank -f ./seeds/seed.nouns.sql
-- last pull from master: 11-25-19

DELETE FROM nouns; -- clear table for re-seeding

INSERT INTO nouns (category, singular, plural, prep, theme)
VALUES
    ('abstract','anger',NULL,NULL,NULL),
    ('abstract','anthropology',NULL,NULL,'modern'),
    ('abstract','archaeology',NULL,NULL,'modern'),
    ('abstract','art',NULL,NULL,NULL),
    ('abstract','authority',NULL,NULL,NULL),
    ('abstract','aviation',NULL,NULL,'modern'),
    ('abstract','biology',NULL,NULL,NULL),
    ('abstract','chaos',NULL,NULL,NULL),
    ('abstract','conciousness',NULL,NULL,NULL),
    ('abstract','confusion',NULL,NULL,NULL),
    ('abstract','cosmology',NULL,NULL,NULL),
    ('abstract','cybernetics',NULL,NULL,'scifi'),
    ('abstract','deception',NULL,NULL,NULL),
    ('abstract','desire',NULL,NULL,NULL),
    ('abstract','despair',NULL,NULL,NULL),
    ('abstract','destiny',NULL,NULL,NULL),
    ('abstract','diplomacy',NULL,NULL,NULL),
    ('abstract','dreams',NULL,NULL,NULL),
    ('abstract','duty',NULL,NULL,NULL),
    ('abstract','ecology',NULL,NULL,'modern'),
    ('abstract','economics',NULL,NULL,NULL),
    ('abstract','emptiness',NULL,NULL,NULL),
    ('abstract','equality',NULL,NULL,NULL),
    ('abstract','espionage',NULL,NULL,NULL),
    ('abstract','euphoria',NULL,NULL,NULL),
    ('abstract','fate',NULL,NULL,NULL),
    ('abstract','fear',NULL,NULL,NULL),
    ('abstract','freedom',NULL,NULL,NULL),
    ('abstract','growth',NULL,NULL,NULL),
    ('abstract','hapiness',NULL,NULL,NULL),
    ('abstract','hard work',NULL,NULL,NULL),
    ('abstract','hatred',NULL,NULL,NULL),
    ('abstract','history',NULL,NULL,NULL),
    ('abstract','hope',NULL,NULL,NULL),
    ('abstract','hubris',NULL,NULL,NULL),
    ('abstract','ignorance',NULL,NULL,NULL),
    ('abstract','imagination',NULL,NULL,NULL),
    ('abstract','journalism',NULL,NULL,'modern'),
    ('abstract','justice',NULL,NULL,NULL),
    ('abstract','knowledge',NULL,NULL,NULL),
    ('abstract','language',NULL,NULL,NULL),
    ('abstract','laziness',NULL,NULL,NULL),
    ('abstract','liberty',NULL,NULL,NULL),
    ('abstract','literature',NULL,NULL,NULL),
    ('abstract','loss',NULL,NULL,NULL),
    ('abstract','love',NULL,NULL,NULL),
    ('abstract','magic',NULL,NULL,'fantasy'),
    ('abstract','medicine',NULL,NULL,NULL),
    ('abstract','memes',NULL,NULL,'modern'),
    ('abstract','memory',NULL,NULL,NULL),
    ('abstract','music',NULL,NULL,NULL),
    ('abstract','mystery',NULL,NULL,NULL),
    ('abstract','nightmares',NULL,NULL,NULL),
    ('abstract','oppulence',NULL,NULL,NULL),
    ('abstract','order',NULL,NULL,NULL),
    ('abstract','pain',NULL,NULL,NULL),
    ('abstract','paleontology',NULL,NULL,'modern'),
    ('abstract','peace',NULL,NULL,NULL),
    ('abstract','philosophy',NULL,NULL,NULL),
    ('abstract','physics',NULL,NULL,'modern'),
    ('abstract','poetry',NULL,NULL,NULL),
    ('abstract','privacy',NULL,NULL,NULL),
    ('abstract','procrastination',NULL,NULL,NULL),
    ('abstract','psychiatry',NULL,NULL,'modern'),
    ('abstract','rage',NULL,NULL,NULL),
    ('abstract','reality',NULL,NULL,NULL),
    ('abstract','religion',NULL,NULL,NULL),
    ('abstract','righteousness',NULL,NULL,NULL),
    ('abstract','robotics',NULL,NULL,'scifi'),
    ('abstract','rocketry',NULL,NULL,'modern'),
    ('abstract','sadness',NULL,NULL,NULL),
    ('abstract','schadenfreude',NULL,NULL,NULL),
    ('abstract','science',NULL,NULL,NULL),
    ('abstract','security',NULL,NULL,NULL),
    ('abstract','servitude',NULL,NULL,NULL),
    ('abstract','sleep',NULL,NULL,NULL),
    ('abstract','sociology',NULL,NULL,'modern'),
    ('abstract','solitude',NULL,NULL,NULL),
    ('abstract','sonder',NULL,NULL,NULL),
    ('abstract','sorcery',NULL,NULL,'fantasy'),
    ('abstract','sports',NULL,NULL,NULL),
    ('abstract','squalor',NULL,NULL,NULL),
    ('abstract','technology',NULL,NULL,NULL),
    ('abstract','the ineffable',NULL,NULL,NULL),
    ('abstract','time',NULL,NULL,NULL),
    ('abstract','time travel',NULL,NULL,'scifi'),
    ('abstract','truth',NULL,NULL,NULL),
    ('abstract','TV sports',NULL,NULL,'modern'),
    ('abstract','urban planning',NULL,NULL,'modern'),
    ('abstract','vexation',NULL,NULL,NULL),
    ('abstract','wizardry',NULL,NULL,'fantasy'),
    ('abstract','wrath',NULL,NULL,NULL),
    ('abstract','wrongfulness',NULL,NULL,NULL),
    ('animate','A.I.','A.I.s',NULL,'scifi'),
    ('animate','aardvark','aardvarks',NULL,NULL),
    ('animate','activist','activists',NULL,'modern'),
    ('animate','actor','actors',NULL,NULL),
    ('animate','actress','actresses',NULL,NULL),
    ('animate','administrator','administrators',NULL,NULL),
    ('animate','admiral','admirals',NULL,NULL),
    ('animate','advisor','advisors',NULL,NULL),
    ('animate','alchemist','alchemists',NULL,'historic'),
    ('animate','alien','aliens',NULL,'scifi'),
    ('animate','ambassador','ambassadors',NULL,NULL),
    ('animate','android','androids',NULL,'scifi'),
    ('animate','angel','angels',NULL,'fantasy'),
    ('animate','ant','ants',NULL,NULL),
    ('animate','anthropologist','anthropologists',NULL,'modern'),
    ('animate','ape','apes',NULL,NULL),
    ('animate','apprentice','apprentices',NULL,NULL),
    ('animate','archaeologist','archaeologists',NULL,'modern'),
    ('animate','archer','archers',NULL,'historic'),
    ('animate','architect','architects',NULL,NULL),
    ('animate','aristrocrat','aristocrats',NULL,NULL),
    ('animate','arsonist','arsonists',NULL,NULL),
    ('animate','artist','artists',NULL,NULL),
    ('animate','assassin','assassins',NULL,NULL),
    ('animate','astrologer','astrologers',NULL,NULL),
    ('animate','astronaut','astronauts',NULL,'modern'),
    ('animate','astronomer','astronomers',NULL,NULL),
    ('animate','athlete','athletes',NULL,NULL),
    ('animate','aunt','aunts',NULL,NULL),
    ('animate','author','authors',NULL,NULL),
    ('animate','baby','babies',NULL,NULL),
    ('animate','babysitter','babysitters',NULL,'modern'),
    ('animate','badger','badgers',NULL,NULL),
    ('animate','baker','bakers',NULL,NULL),
    ('animate','ballerina','ballerinas',NULL,'modern'),
    ('animate','bandit','bandits',NULL,NULL),
    ('animate','banker','bankers',NULL,NULL),
    ('animate','banshee','banshees',NULL,'fantasy'),
    ('animate','barbarian','barbarians',NULL,'historic'),
    ('animate','barber','barbers',NULL,NULL),
    ('animate','bard','bards',NULL,'historic'),
    ('animate','barista','baristas',NULL,NULL),
    ('animate','baron','barons',NULL,'historic'),
    ('animate','baroness','baronesses',NULL,'historic'),
    ('animate','bartender','bartenders',NULL,NULL),
    ('animate','basilisk','basilisks',NULL,'fantasy'),
    ('animate','bat','bats',NULL,NULL),
    ('animate','bear','bears',NULL,NULL),
    ('animate','beast','beasts',NULL,'fantasy'),
    ('animate','beautician','beauticians',NULL,'modern'),
    ('animate','beaver','beavers',NULL,NULL),
    ('animate','bee','bees',NULL,NULL),
    ('animate','beetle','beetles',NULL,NULL),
    ('animate','beggar','beggars',NULL,NULL),
    ('animate','bigfoot','bigfoots',NULL,'modern'),
    ('animate','biker','bikers',NULL,'modern'),
    ('animate','billionaire','billionaires',NULL,NULL),
    ('animate','biologist','biologists',NULL,NULL),
    ('animate','bird','birds',NULL,NULL),
    ('animate','bishop','bishops',NULL,NULL),
    ('animate','black-belt','black-belts',NULL,'modern'),
    ('animate','blogger','bloggers',NULL,'modern'),
    ('animate','boa constrictor','boa constrictors',NULL,NULL),
    ('animate','boar','boars',NULL,NULL),
    ('animate','bobcat','bobcat',NULL,NULL),
    ('animate','body builder','body builder',NULL,'modern'),
    ('animate','boy','boys',NULL,NULL),
    ('animate','brewer','brewer',NULL,NULL),
    ('animate','brigand','brigand',NULL,'historic'),
    ('animate','brother','brothers',NULL,NULL),
    ('animate','brother-in-law','brothers-in-law',NULL,NULL),
    ('animate','bug','bug',NULL,NULL),
    ('animate','bull','bulls',NULL,NULL),
    ('animate','bully','bullies',NULL,NULL),
    ('animate','burglar','burglars',NULL,NULL),
    ('animate','businessman','businessmen',NULL,NULL),
    ('animate','businesswoman','businesswomen',NULL,NULL),
    ('animate','butler','butler',NULL,NULL),
    ('animate','butterfly','butterflies',NULL,NULL),
    ('animate','cabin boy','cabin boys',NULL,'historic'),
    ('animate','caliph','caliphs',NULL,NULL),
    ('animate','captain','captains',NULL,NULL),
    ('animate','capybara','capybaras',NULL,NULL),
    ('animate','carpenter','carpenters',NULL,NULL),
    ('animate','cartographer','cartograhpers',NULL,NULL),
    ('animate','cashier','cashiers',NULL,'modern'),
    ('animate','cat','cats',NULL,NULL),
    ('animate','caterpillar','caterpillars',NULL,NULL),
    ('animate','cave man','cave men',NULL,NULL),
    ('animate','cave woman','cave women',NULL,NULL),
    ('animate','celebrity','celebrities',NULL,'modern'),
    ('animate','centaur','centaurs',NULL,'fantasy'),
    ('animate','centurion','centurions',NULL,'historic'),
    ('animate','CEO','CEOs',NULL,'modern'),
    ('animate','CFO','CFOs',NULL,'modern'),
    ('animate','chancellor','chancellors',NULL,NULL),
    ('animate','chaplain','chaplains',NULL,NULL),
    ('animate','chauffeur','chauffeurs',NULL,'modern'),
    ('animate','cheerleader','cheerleaders',NULL,'modern'),
    ('animate','cheetah','cheetahs',NULL,NULL),
    ('animate','chef','chefs',NULL,NULL),
    ('animate','chemist','chemists',NULL,NULL),
    ('animate','cherub','cherubim',NULL,'fantasy'),
    ('animate','chessmaster','chessmasters',NULL,'modern'),
    ('animate','chicken','chickens',NULL,NULL),
    ('animate','chieftan','chieftans',NULL,'historic'),
    ('animate','child','children',NULL,NULL),
    ('animate','chimera','chimeras',NULL,'fantasy'),
    ('animate','chipmunk','chipmunks',NULL,NULL),
    ('animate','cinematographer','cinematographers',NULL,'modern'),
    ('animate','clam','clams',NULL,NULL),
    ('animate','clown','clowns',NULL,NULL),
    ('animate','cobra','cobras',NULL,NULL),
    ('animate','coelacanth','coelacanths',NULL,NULL),
    ('animate','comedian','comedians',NULL,NULL),
    ('animate','con artist','con artists',NULL,NULL),
    ('animate','concierge','concierges',NULL,'modern'),
    ('animate','concubine','concubines',NULL,'historic'),
    ('animate','construction worker','construction workers',NULL,'modern'),
    ('animate','cook','cooks',NULL,NULL),
    ('animate','cop','cops',NULL,'modern'),
    ('animate','cosmonaut','cosmonauts',NULL,'modern'),
    ('animate','count','counts',NULL,'historic'),
    ('animate','countess','countesses',NULL,'historic'),
    ('animate','courier','couriers',NULL,NULL),
    ('animate','courtesan','courtesans',NULL,NULL),
    ('animate','cousin','cousins',NULL,NULL),
    ('animate','cow','cows',NULL,NULL),
    ('animate','cowboy','cowboys',NULL,'modern'),
    ('animate','cowgirl','cowgirls',NULL,'modern'),
    ('animate','coyote','coyotes',NULL,NULL),
    ('animate','cricket','crickets',NULL,NULL),
    ('animate','crow','crows',NULL,NULL),
    ('animate','crusader','crusaders',NULL,'historic'),
    ('animate','CTO','CTOs',NULL,'modern'),
    ('animate','cyclist','cyclists',NULL,NULL),
    ('animate','cyclops','cyclopes',NULL,'fantasy'),
    ('animate','dad','dads',NULL,NULL),
    ('animate','dancer','dancers',NULL,NULL),
    ('animate','daughter','daughters',NULL,NULL),
    ('animate','daughter-in-law','daughters-in-law',NULL,NULL),
    ('animate','debutante','debutantes',NULL,NULL),
    ('animate','deer','deer',NULL,NULL),
    ('animate','demon','demons',NULL,'fantasy'),
    ('animate','detective','detectives',NULL,'modern'),
    ('animate','dictator','dictators',NULL,'modern'),
    ('animate','dinosaur','dinosaurs',NULL,'fantasy'),
    ('animate','diplomat','diplomats',NULL,NULL),
    ('animate','DJ','DJs',NULL,'modern'),
    ('animate','doctor','doctors',NULL,NULL),
    ('animate','dog','dogs',NULL,NULL),
    ('animate','dolphin','dolphins',NULL,NULL),
    ('animate','donkey','donkies',NULL,NULL),
    ('animate','dove','doves',NULL,NULL),
    ('animate','dragon','dragons',NULL,'fantasy'),
    ('animate','drudge','drudges',NULL,'historic'),
    ('animate','druid','druids',NULL,'fantasy'),
    ('animate','drunkard','drunkards',NULL,NULL),
    ('animate','duchess','duchesses',NULL,'historic'),
    ('animate','duck','ducks',NULL,NULL),
    ('animate','duke','dukes',NULL,'historic'),
    ('animate','dwarf','dwarves',NULL,'fantasy'),
    ('animate','eagle','eagles',NULL,NULL),
    ('animate','editor','editors',NULL,'modern'),
    ('animate','eel','eels',NULL,NULL),
    ('animate','electrictian','electrician',NULL,'modern'),
    ('animate','elephant','elephants',NULL,NULL),
    ('animate','elf','elves',NULL,'fantasy'),
    ('animate','elk','elks',NULL,NULL),
    ('animate','emperor','emperors',NULL,'historic'),
    ('animate','empress','empresses',NULL,'historic'),
    ('animate','enemy','enemies',NULL,NULL),
    ('animate','engineer','engineers',NULL,NULL),
    ('animate','entity','entities',NULL,'fantasy'),
    ('animate','entrepeneur','entrepeneurs',NULL,NULL),
    ('animate','eunuch','eunuchs',NULL,'historic'),
    ('animate','evangelist','evangelists',NULL,NULL),
    ('animate','fairy','faries',NULL,'fantasy'),
    ('animate','farmer','farmers',NULL,NULL),
    ('animate','father','fathers',NULL,NULL),
    ('animate','father-in-law','fathers-in-law',NULL,NULL),
    ('animate','felon','felons',NULL,'modern'),
    ('animate','ferret','ferrets',NULL,NULL),
    ('animate','filmmaker','filmmakers',NULL,'modern'),
    ('animate','firefighter','firefighters',NULL,'modern'),
    ('animate','fish','fish',NULL,NULL),
    ('animate','fisherman','fishermen',NULL,NULL),
    ('animate','flight attendant','flight attendants',NULL,'modern'),
    ('animate','fly','flies',NULL,NULL),
    ('animate','foal','foals',NULL,NULL),
    ('animate','foodtruck driver','foodtruck drivers',NULL,'modern'),
    ('animate','fool','fools',NULL,NULL),
    ('animate','foreman','foremen',NULL,'modern'),
    ('animate','fox','foxes',NULL,NULL),
    ('animate','friar','friars',NULL,'fantasy'),
    ('animate','friend','friends',NULL,NULL),
    ('animate','frog','frogs',NULL,NULL),
    ('animate','fugitive','fugitives',NULL,NULL),
    ('animate','gambler','gamblers',NULL,NULL),
    ('animate','gamer','gamers',NULL,'modern'),
    ('animate','gangster','gangsters',NULL,'modern'),
    ('animate','gecko','geckos',NULL,NULL),
    ('animate','geisha','geishas',NULL,NULL),
    ('animate','general','generals',NULL,NULL),
    ('animate','genie','genies',NULL,'fantasy'),
    ('animate','genius','geniuses',NULL,NULL),
    ('animate','gentleman','gentlemen',NULL,NULL),
    ('animate','ghost','ghosts',NULL,'fantasy'),
    ('animate','giant','giants',NULL,'fantasy'),
    ('animate','giraffe','giraffes',NULL,NULL),
    ('animate','girl','girls',NULL,NULL),
    ('animate','gladiator','gladiators',NULL,'historic'),
    ('animate','gnome','gnomes',NULL,'fantasy'),
    ('animate','goalie','goalies',NULL,'modern'),
    ('animate','goat','gots',NULL,NULL),
    ('animate','goblin','goblins',NULL,'fantasy'),
    ('animate','god','gods',NULL,NULL),
    ('animate','goddess','goddesses',NULL,NULL),
    ('animate','golem','golems',NULL,'fantasy'),
    ('animate','goose','geese',NULL,NULL),
    ('animate','gopher','gophers',NULL,NULL),
    ('animate','gorgon','gogons',NULL,'fantasy'),
    ('animate','gorilla','gorillas',NULL,NULL),
    ('animate','grandfather','grandfathers',NULL,NULL),
    ('animate','grandma','grandmas',NULL,NULL),
    ('animate','grandmother','grandmothers',NULL,NULL),
    ('animate','grandpa','grandpas',NULL,NULL),
    ('animate','grasshopper','grashoppers',NULL,NULL),
    ('animate','gravedigger','gravediggers',NULL,NULL),
    ('animate','graverobber','graverobbers',NULL,NULL),
    ('animate','great aunt','great aunts',NULL,NULL),
    ('animate','great uncle','great uncles',NULL,NULL),
    ('animate','grizzly bear','grizzly bears',NULL,NULL),
    ('animate','groundskeeper','groundskeepers',NULL,NULL),
    ('animate','gryphon','gryphons',NULL,'fantasy'),
    ('animate','hacker','hackers',NULL,'modern'),
    ('animate','hen','hens',NULL,NULL),
    ('animate','hippie','hippies',NULL,NULL),
    ('animate','hippopotamus','hippopotami',NULL,NULL),
    ('animate','hobgoblin','hobgoblins',NULL,'fantasy'),
    ('animate','hobo','hobos',NULL,NULL),
    ('animate','hog','hogs',NULL,NULL),
    ('animate','hornet','hornets',NULL,NULL),
    ('animate','horse','horses',NULL,NULL),
    ('animate','housekeeper','housekeepers',NULL,NULL),
    ('animate','hummingbird','hummingbirds',NULL,NULL),
    ('animate','hunter','hunters',NULL,NULL),
    ('animate','husband','husbands',NULL,NULL),
    ('animate','hyena','hyenas',NULL,NULL),
    ('animate','idiot','idiots',NULL,NULL),
    ('animate','iguana','iguanas',NULL,NULL),
    ('animate','imam','imams',NULL,NULL),
    ('animate','inmate','inmates',NULL,'modern'),
    ('animate','inquisitor','inquisitors',NULL,'historic'),
    ('animate','insomniac','insomniacs',NULL,NULL),
    ('animate','inspector','inspectors',NULL,NULL),
    ('animate','inventor','inventors',NULL,NULL),
    ('animate','investor','investors',NULL,'modern'),
    ('animate','jaguar','jaguars',NULL,NULL),
    ('animate','jellyfish','jellyfish',NULL,NULL),
    ('animate','jester','jesters',NULL,NULL),
    ('animate','jihadi','jihadis',NULL,'historic'),
    ('animate','jogger','joggers',NULL,NULL),
    ('animate','journalist','journalists',NULL,'modern'),
    ('animate','judge','judges',NULL,NULL),
    ('animate','juggler','jugglers',NULL,NULL),
    ('animate','kangaroo','kangaroos',NULL,NULL),
    ('animate','kid','kids',NULL,NULL),
    ('animate','kings','king',NULL,'historic'),
    ('animate','kitten','kittens',NULL,NULL),
    ('animate','knight','knight',NULL,'historic'),
    ('animate','laborer','laborers',NULL,NULL),
    ('animate','lady','ladies',NULL,NULL),
    ('animate','lama','lamas',NULL,NULL),
    ('animate','landlord','landlords',NULL,NULL),
    ('animate','lawmaker','lawmakers',NULL,NULL),
    ('animate','lawyer','lawyers',NULL,'modern'),
    ('animate','leapord','leapords',NULL,NULL),
    ('animate','legionnaire','legionnaires',NULL,'historic'),
    ('animate','lemur','lemurs',NULL,NULL),
    ('animate','leper','lepers',NULL,NULL),
    ('animate','leprechaun','leprechauns',NULL,'fantasy'),
    ('animate','librarian','librarians',NULL,NULL),
    ('animate','lieutenant','lieutenants',NULL,NULL),
    ('animate','linebacker','linebackers',NULL,'modern'),
    ('animate','lion','lions',NULL,NULL),
    ('animate','lioness','lionesses',NULL,NULL),
    ('animate','lizard','lizards',NULL,NULL),
    ('animate','llama','llamas',NULL,NULL),
    ('animate','lord','lords',NULL,'historic'),
    ('animate','lynx','lynxes',NULL,NULL),
    ('animate','magician','magicians',NULL,NULL),
    ('animate','magistrate','magistrates',NULL,'historic'),
    ('animate','maid','maids',NULL,NULL),
    ('animate','mammoth','mammoths',NULL,'historic'),
    ('animate','man','men',NULL,NULL),
    ('animate','manager','manager',NULL,'modern'),
    ('animate','marine','marines',NULL,'modern'),
    ('animate','marlin','marlins',NULL,NULL),
    ('animate','marshal','marshals',NULL,NULL),
    ('animate','mason','masons',NULL,NULL),
    ('animate','mastadon','mastadons',NULL,'historic'),
    ('animate','mathematician','mathematicians',NULL,NULL),
    ('animate','matriarch','matriarchs',NULL,NULL),
    ('animate','mayor','mayors',NULL,NULL),
    ('animate','mechanic','mechanics',NULL,'modern'),
    ('animate','mermaid','mermaids',NULL,'fantasy'),
    ('animate','merman','mermen',NULL,'fantasy'),
    ('animate','midwife','midwives',NULL,NULL),
    ('animate','millionaire','millionaires',NULL,NULL),
    ('animate','mime','mimes',NULL,NULL),
    ('animate','miner','miners',NULL,NULL),
    ('animate','mobster','mobsters',NULL,NULL),
    ('animate','model','models',NULL,NULL),
    ('animate','mollusk','mollusks',NULL,NULL),
    ('animate','mom','moms',NULL,NULL),
    ('animate','monk','monks',NULL,NULL),
    ('animate','monkey','monkies',NULL,NULL),
    ('animate','monster','monsters',NULL,'fantasy'),
    ('animate','moose','moose',NULL,NULL),
    ('animate','mortician','morticians',NULL,NULL),
    ('animate','moth','moths',NULL,NULL),
    ('animate','mother','mothers',NULL,NULL),
    ('animate','mother-in-law','mothers-in-law',NULL,NULL),
    ('animate','mountaineer','mountaineers',NULL,NULL),
    ('animate','mouse','mice',NULL,NULL),
    ('animate','moutain lion','mountain lions',NULL,NULL),
    ('animate','mule','mules',NULL,NULL),
    ('animate','murderer','murderers',NULL,NULL),
    ('animate','muse','muses',NULL,NULL),
    ('animate','musician','musicians',NULL,NULL),
    ('animate','mussel','mussels',NULL,NULL),
    ('animate','nanny','nannies',NULL,NULL),
    ('animate','news anchor','news anchors',NULL,'modern'),
    ('animate','ninja','ninjas',NULL,'historic'),
    ('animate','novelist','novelists',NULL,'modern'),
    ('animate','nun','nuns',NULL,NULL),
    ('animate','nurse','nurses',NULL,NULL),
    ('animate','octopus','octopi',NULL,NULL),
    ('animate','ogre','ogres',NULL,'fantasy'),
    ('animate','optometrist','optometrists',NULL,'modern'),
    ('animate','oracle','oracles',NULL,'fantasy'),
    ('animate','orangutan','orangutans',NULL,NULL),
    ('animate','orca','orcas',NULL,NULL),
    ('animate','orphan','orphans',NULL,NULL),
    ('animate','otolaryngologist','otolaryngologists',NULL,'modern'),
    ('animate','outlaw','outlaws',NULL,NULL),
    ('animate','owl','owls',NULL,NULL),
    ('animate','oyster','oysters',NULL,NULL),
    ('animate','painter','painters',NULL,NULL),
    ('animate','paleontologist','paleontologists',NULL,'modern'),
    ('animate','panda','pandas',NULL,NULL),
    ('animate','patriarch','patriarchs',NULL,NULL),
    ('animate','peacock','peacocks',NULL,NULL),
    ('animate','peasant','peasants',NULL,'historic'),
    ('animate','pelican','pelicans',NULL,NULL),
    ('animate','penguin','penguins',NULL,NULL),
    ('animate','pharmacist','pharmacists',NULL,NULL),
    ('animate','philanthropist','philanthropists',NULL,NULL),
    ('animate','philosopher','philosophers',NULL,NULL),
    ('animate','physicist','physicists',NULL,NULL),
    ('animate','pig','pigs',NULL,NULL),
    ('animate','pigeon','pigeons',NULL,NULL),
    ('animate','piglet','piglets',NULL,NULL),
    ('animate','pilgrim','pilgrims',NULL,NULL),
    ('animate','pilot','pilots',NULL,'modern'),
    ('animate','pioneer','pioneers',NULL,NULL),
    ('animate','pirate','pirates',NULL,'historic'),
    ('animate','plumber','plumbers',NULL,'modern'),
    ('animate','poet','poets',NULL,NULL),
    ('animate','polar bear','polar bears',NULL,NULL),
    ('animate','politician','politicians',NULL,NULL),
    ('animate','pope','popes',NULL,NULL),
    ('animate','prarie dog','prarie dogs',NULL,NULL),
    ('animate','prepper','preppers',NULL,'modern'),
    ('animate','president','presidents',NULL,'modern'),
    ('animate','priest','priests',NULL,NULL),
    ('animate','priestess','priestesses',NULL,NULL),
    ('animate','prince','princes',NULL,'historic'),
    ('animate','princess','princesses',NULL,'historic'),
    ('animate','prisoner','prisoners',NULL,NULL),
    ('animate','professor','professors',NULL,'modern'),
    ('animate','programmer','promgrammers',NULL,'modern'),
    ('animate','prophet','prophets',NULL,NULL),
    ('animate','prospector','prospectors',NULL,'modern'),
    ('animate','protestor','protestors',NULL,NULL),
    ('animate','psychiatrist','psychiatrists',NULL,'modern'),
    ('animate','publisher','publishers',NULL,'modern'),
    ('animate','puma','pumas',NULL,NULL),
    ('animate','puppeteer','puppeteers',NULL,NULL),
    ('animate','puppy','puppies',NULL,NULL),
    ('animate','python','pythons',NULL,NULL),
    ('animate','quagga','quagga',NULL,'historic'),
    ('animate','quarterback','quarterback',NULL,'modern'),
    ('animate','queen','queen',NULL,'historic'),
    ('animate','rabbi','rabbis',NULL,NULL),
    ('animate','rabbit','rabbits',NULL,NULL),
    ('animate','racecar driver','racecar drivers',NULL,'modern'),
    ('animate','rancher','ranchers',NULL,NULL),
    ('animate','ranger','rangers',NULL,NULL),
    ('animate','rat','rats',NULL,NULL),
    ('animate','raven','ravens',NULL,NULL),
    ('animate','raver','ravers',NULL,'modern'),
    ('animate','rebel','rebels',NULL,NULL),
    ('animate','refugee','refugees',NULL,NULL),
    ('animate','reindeer','reindeer',NULL,NULL),
    ('animate','researcher','researchers',NULL,NULL),
    ('animate','reverend','reverends',NULL,NULL),
    ('animate','rhinoceros','rhinoceros',NULL,NULL),
    ('animate','robot','robots',NULL,'scifi'),
    ('animate','rockstar','rockstars',NULL,'modern'),
    ('animate','rooster','roosters',NULL,NULL),
    ('animate','saber-toothed tiger','saber-toothed tigers',NULL,'historic'),
    ('animate','sailor','sailors',NULL,NULL),
    ('animate','saint','saints',NULL,NULL),
    ('animate','salmon','salmons',NULL,NULL),
    ('animate','samurai','samurai',NULL,'historic'),
    ('animate','sasquatch','sasquatches',NULL,'fantasy'),
    ('animate','satyr','satyrs',NULL,'fantasy'),
    ('animate','savant','savants',NULL,NULL),
    ('animate','scholar','scholars',NULL,NULL),
    ('animate','scientist','scientists',NULL,'modern'),
    ('animate','scout','scouts',NULL,NULL),
    ('animate','scuba diver','scuba divers',NULL,'modern'),
    ('animate','sculptor','sculptors',NULL,NULL),
    ('animate','seamstress','seamstresses',NULL,NULL),
    ('animate','secretary','secretaries',NULL,NULL),
    ('animate','security guard','security guards',NULL,NULL),
    ('animate','seer','seers',NULL,'fantasy'),
    ('animate','senator','senators',NULL,NULL),
    ('animate','sergeant','sergeants',NULL,NULL),
    ('animate','servant','servants',NULL,NULL),
    ('animate','server','servers',NULL,NULL),
    ('animate','shark','sharks',NULL,NULL),
    ('animate','sheep','sheep',NULL,NULL),
    ('animate','sheriff','sheriffs',NULL,'modern'),
    ('animate','singer','singers',NULL,NULL),
    ('animate','singer-songwriter','singer-songwriters',NULL,'modern'),
    ('animate','siren','sirens',NULL,'fantasy'),
    ('animate','sister','sisters',NULL,NULL),
    ('animate','sister-in-law','sisters-in-law',NULL,NULL),
    ('animate','skeleton','skeletons',NULL,'fantasy'),
    ('animate','skunk','skunks',NULL,NULL),
    ('animate','slave','slaves',NULL,NULL),
    ('animate','sleuth','sleuths',NULL,'modern'),
    ('animate','slug','slugs',NULL,NULL),
    ('animate','smith','smiths',NULL,'historic'),
    ('animate','snail','snails',NULL,NULL),
    ('animate','snake','snakes',NULL,NULL),
    ('animate','sociologist','sociologists',NULL,'modern'),
    ('animate','soldier','soldiers',NULL,NULL),
    ('animate','son','sons',NULL,NULL),
    ('animate','son-in-law','sons-in-law',NULL,NULL),
    ('animate','sorceress','sorceresses',NULL,'fantasy'),
    ('animate','sorceror','sorcerors',NULL,'fantasy'),
    ('animate','sous chef','sous chefs',NULL,NULL),
    ('animate','space marine','space marines',NULL,'scifi'),
    ('animate','space ranger','space rangers',NULL,'scifi'),
    ('animate','spectre','spectres',NULL,'fantasy'),
    ('animate','spider','spiders',NULL,NULL),
    ('animate','spirit','spirits',NULL,NULL),
    ('animate','sports fan','sports fans',NULL,NULL),
    ('animate','spy','spies',NULL,NULL),
    ('animate','squatter','squatters',NULL,NULL),
    ('animate','squid','squids',NULL,NULL),
    ('animate','squire','squires',NULL,'historic'),
    ('animate','squirrel','squirrels',NULL,NULL),
    ('animate','starfish','starfish',NULL,NULL),
    ('animate','statesman','statesmen',NULL,NULL),
    ('animate','stepbrother','stepbrothers',NULL,NULL),
    ('animate','stepdaughter','stepdaughters',NULL,NULL),
    ('animate','stepfather','stepfathers',NULL,NULL),
    ('animate','stepmother','stepmothers',NULL,NULL),
    ('animate','stepsister','stepsisters',NULL,NULL),
    ('animate','stepson','stepsons',NULL,NULL),
    ('animate','stingray','stingrays',NULL,NULL),
    ('animate','stock broker','stock brokers',NULL,'modern'),
    ('animate','stranger','strangers',NULL,NULL),
    ('animate','student','students',NULL,NULL),
    ('animate','stunt double','stunt doubles',NULL,NULL),
    ('animate','suitor','suitors',NULL,NULL),
    ('animate','sultan','sultans',NULL,'historic'),
    ('animate','sultana','sultanas',NULL,'historic'),
    ('animate','superhero','superheroes',NULL,'modern'),
    ('animate','supervillain','supervillains',NULL,'modern'),
    ('animate','surgeon','surgeons',NULL,'modern'),
    ('animate','swan','swans',NULL,NULL),
    ('animate','swimmer','swimmers',NULL,NULL),
    ('animate','tanuki','tanuki',NULL,NULL),
    ('animate','tapir','tapirs',NULL,NULL),
    ('animate','taxedermist','taxedermists',NULL,NULL),
    ('animate','taxi driver','taxi drivers',NULL,'modern'),
    ('animate','teacher','teachers',NULL,NULL),
    ('animate','televangelist','televangelists',NULL,'modern'),
    ('animate','termite','termites',NULL,NULL),
    ('animate','terrorist','terrorists',NULL,NULL),
    ('animate','theif','theives',NULL,NULL),
    ('animate','therapist','therapists',NULL,'modern'),
    ('animate','tiger','tigers',NULL,NULL),
    ('animate','titan','titans',NULL,'fantasy'),
    ('animate','toad','toads',NULL,NULL),
    ('animate','tortoise','tortoises',NULL,NULL),
    ('animate','tour guide','tour guides',NULL,NULL),
    ('animate','tourist','tourists',NULL,'modern'),
    ('animate','trader','traders',NULL,'historic'),
    ('animate','tree','trees',NULL,'fantasy'),
    ('animate','tree frog','tree frogs',NULL,NULL),
    ('animate','trickster','trickers',NULL,NULL),
    ('animate','troll','trolls',NULL,'fantasy'),
    ('animate','trout','trouts',NULL,NULL),
    ('animate','truck driver','truck drivers',NULL,'modern'),
    ('animate','turkey','turkeys',NULL,NULL),
    ('animate','turtle','turtle',NULL,NULL),
    ('animate','twin','twin',NULL,NULL),
    ('animate','typist','typists',NULL,'modern'),
    ('animate','uncle','uncles',NULL,NULL),
    ('animate','unicorn','unicorns',NULL,'fantasy'),
    ('animate','urchin','urchins',NULL,NULL),
    ('animate','vagrant','vagrants',NULL,NULL),
    ('animate','vampire','vampires',NULL,'fantasy'),
    ('animate','veteran','veterans',NULL,NULL),
    ('animate','viceroy','viceroys',NULL,'historic'),
    ('animate','viking','vikings',NULL,'historic'),
    ('animate','voyageur','voyageurs',NULL,'historic'),
    ('animate','waiter','waiters',NULL,NULL),
    ('animate','waitress','waitresses',NULL,NULL),
    ('animate','wallabee','wallabees',NULL,NULL),
    ('animate','walrus','walruses',NULL,NULL),
    ('animate','warden','wardens',NULL,NULL),
    ('animate','warlock','warlocks',NULL,'fantasy'),
    ('animate','warlord','warlords',NULL,'historic'),
    ('animate','warrior','warriors',NULL,NULL),
    ('animate','warthog','warthogs',NULL,NULL),
    ('animate','wasp','wasps',NULL,NULL),
    ('animate','welder','welders',NULL,'modern'),
    ('animate','whale','whales',NULL,NULL),
    ('animate','widow','widows',NULL,NULL),
    ('animate','widower','widowers',NULL,NULL),
    ('animate','wife','wives',NULL,NULL),
    ('animate','witch','witches',NULL,'fantasy'),
    ('animate','wizard','wizards',NULL,'fantasy'),
    ('animate','wolf','wolves',NULL,NULL),
    ('animate','woman','women',NULL,NULL),
    ('animate','wombat','wombats',NULL,NULL),
    ('animate','woodpecker','woodpeckers',NULL,NULL),
    ('animate','worm','worms',NULL,NULL),
    ('animate','wrestler','wrestlers',NULL,NULL),
    ('animate','yeti','yetis',NULL,'fantasy'),
    ('animate','yogi','yogis',NULL,NULL),
    ('animate','zebra','zebras',NULL,NULL),
    ('animate','zen master','zen masters',NULL,NULL),
    ('animate','zombie','zombies',NULL,'fantasy'),
    ('animate','zookeeper','zookeepers',NULL,NULL),
    ('container','backpack','backpacks',NULL,NULL),
    ('container','bag','bags',NULL,NULL),
    ('container','barrel','barrels',NULL,NULL),
    ('container','basket','baskets',NULL,NULL),
    ('container','bin','bins',NULL,NULL),
    ('container','bindle','bindles',NULL,NULL),
    ('container','box','boxes',NULL,NULL),
    ('container','briefcase','briefcases',NULL,'modern'),
    ('container','bucket','buckets',NULL,NULL),
    ('container','can','cans',NULL,NULL),
    ('container','canister','canisters',NULL,NULL),
    ('container','carton','cartons',NULL,NULL),
    ('container','chest','chests',NULL,NULL),
    ('container','container','containers',NULL,NULL),
    ('container','crate','crates',NULL,NULL),
    ('container','database','databases',NULL,'scifi'),
    ('container','duffel bag','duffel bags',NULL,'modern'),
    ('container','jar','jars',NULL,NULL),
    ('container','oven','ovens',NULL,NULL),
    ('container','package','packages',NULL,NULL),
    ('container','parcel','parcels',NULL,NULL),
    ('container','refrigerator','refrigerators',NULL,'modern'),
    ('container','reliquary','reliquaries',NULL,'historic'),
    ('container','sack','sacks',NULL,NULL),
    ('container','safe','safes',NULL,NULL),
    ('container','sarcophagus','sarcophagi',NULL,'historic'),
    ('container','satchel','satchels',NULL,NULL),
    ('container','shipping container','shipping containers',NULL,'modern'),
    ('container','suitcase','suitcases',NULL,'modern'),
    ('container','tote bag','tote bags',NULL,'modern'),
    ('container','trunk','trunks',NULL,NULL),
    ('container','tub','tubs',NULL,NULL),
    ('container','vending machine','vending machines',NULL,'modern'),
    ('container','wheelbarrow','wheelbarrows',NULL,NULL),
    ('genre','action movie',NULL,NULL,NULL),
    ('genre','adventure',NULL,NULL,NULL),
    ('genre','allegory',NULL,NULL,NULL),
    ('genre','animation',NULL,NULL,NULL),
    ('genre','anime',NULL,NULL,NULL),
    ('genre','article',NULL,NULL,NULL),
    ('genre','artwork',NULL,NULL,NULL),
    ('genre','autobiography',NULL,NULL,NULL),
    ('genre','ballad',NULL,NULL,NULL),
    ('genre','bedtime story',NULL,NULL,NULL),
    ('genre','biography',NULL,NULL,NULL),
    ('genre','book',NULL,NULL,NULL),
    ('genre','buddy comedy',NULL,NULL,NULL),
    ('genre','comedy',NULL,NULL,NULL),
    ('genre','comic book',NULL,NULL,NULL),
    ('genre','comic strip',NULL,NULL,NULL),
    ('genre','commercial',NULL,NULL,'modern'),
    ('genre','conspiracy',NULL,NULL,NULL),
    ('genre','critique',NULL,NULL,NULL),
    ('genre','disaster',NULL,NULL,NULL),
    ('genre','dissertation',NULL,NULL,NULL),
    ('genre','documentary',NULL,NULL,NULL),
    ('genre','drama',NULL,NULL,NULL),
    ('genre','dream',NULL,NULL,NULL),
    ('genre','epic',NULL,NULL,'historic'),
    ('genre','essay',NULL,NULL,NULL),
    ('genre','fable',NULL,NULL,NULL),
    ('genre','fairy tale',NULL,NULL,'fantasy'),
    ('genre','film',NULL,NULL,NULL),
    ('genre','graphic novel',NULL,NULL,NULL),
    ('genre','hoax',NULL,NULL,NULL),
    ('genre','horror story',NULL,NULL,NULL),
    ('genre','interview',NULL,NULL,NULL),
    ('genre','lecture',NULL,NULL,NULL),
    ('genre','legend',NULL,NULL,'historic'),
    ('genre','limerick',NULL,NULL,NULL),
    ('genre','manga',NULL,NULL,NULL),
    ('genre','memoir',NULL,NULL,NULL),
    ('genre','memory',NULL,NULL,NULL),
    ('genre','miniseries',NULL,NULL,NULL),
    ('genre','misadventure',NULL,NULL,NULL),
    ('genre','movie',NULL,NULL,NULL),
    ('genre','music video',NULL,NULL,NULL),
    ('genre','musical',NULL,NULL,NULL),
    ('genre','mystery',NULL,NULL,NULL),
    ('genre','narrative',NULL,NULL,NULL),
    ('genre','newscast',NULL,NULL,'modern'),
    ('genre','nightmare',NULL,NULL,NULL),
    ('genre','novel',NULL,NULL,NULL),
    ('genre','novella',NULL,NULL,NULL),
    ('genre','opera',NULL,NULL,NULL),
    ('genre','painting',NULL,NULL,NULL),
    ('genre','parable',NULL,NULL,NULL),
    ('genre','parable',NULL,NULL,'historic'),
    ('genre','play',NULL,NULL,NULL),
    ('genre','poem',NULL,NULL,NULL),
    ('genre','prequel',NULL,NULL,NULL),
    ('genre','presentation',NULL,NULL,NULL),
    ('genre','radio play',NULL,NULL,NULL),
    ('genre','reality show',NULL,NULL,NULL),
    ('genre','romance',NULL,NULL,NULL),
    ('genre','saga',NULL,NULL,NULL),
    ('genre','satire',NULL,NULL,NULL),
    ('genre','scripture',NULL,NULL,'historic'),
    ('genre','sculpture',NULL,NULL,NULL),
    ('genre','sequel',NULL,NULL,NULL),
    ('genre','series',NULL,NULL,NULL),
    ('genre','short story',NULL,NULL,NULL),
    ('genre','show',NULL,NULL,NULL),
    ('genre','sitcom',NULL,NULL,NULL),
    ('genre','song',NULL,NULL,NULL),
    ('genre','sonnet',NULL,NULL,NULL),
    ('genre','speech',NULL,NULL,NULL),
    ('genre','spin-off',NULL,NULL,NULL),
    ('genre','standup routine',NULL,NULL,NULL),
    ('genre','story',NULL,NULL,NULL),
    ('genre','tale',NULL,NULL,NULL),
    ('genre','tapestry',NULL,NULL,'historic'),
    ('genre','testimony',NULL,NULL,NULL),
    ('genre','textbook',NULL,NULL,NULL),
    ('genre','thesis',NULL,NULL,NULL),
    ('genre','thriller',NULL,NULL,NULL),
    ('genre','tragedy',NULL,NULL,NULL),
    ('genre','training video',NULL,NULL,'modern'),
    ('genre','transcript',NULL,NULL,'modern'),
    ('genre','trilogy',NULL,NULL,NULL),
    ('genre','video game',NULL,NULL,NULL),
    ('genre','western',NULL,NULL,'historic'),
    ('group','alliance',NULL,NULL,NULL),
    ('group','army',NULL,NULL,NULL),
    ('group','assembly',NULL,NULL,NULL),
    ('group','band',NULL,NULL,NULL),
    ('group','boat full',NULL,NULL,'modern'),
    ('group','bus full',NULL,NULL,'modern'),
    ('group','cabal',NULL,NULL,NULL),
    ('group','cadre',NULL,NULL,NULL),
    ('group','car full',NULL,NULL,'modern'),
    ('group','cartel',NULL,NULL,NULL),
    ('group','choir',NULL,NULL,NULL),
    ('group','clan',NULL,NULL,'historic'),
    ('group','clique',NULL,NULL,NULL),
    ('group','cluster',NULL,NULL,NULL),
    ('group','cohort',NULL,NULL,NULL),
    ('group','company',NULL,NULL,NULL),
    ('group','council',NULL,NULL,NULL),
    ('group','coven',NULL,NULL,NULL),
    ('group','crew',NULL,NULL,NULL),
    ('group','crowd',NULL,NULL,NULL),
    ('group','cult',NULL,NULL,NULL),
    ('group','ensemble',NULL,NULL,NULL),
    ('group','faction',NULL,NULL,NULL),
    ('group','family',NULL,NULL,NULL),
    ('group','gang',NULL,NULL,NULL),
    ('group','gathering',NULL,NULL,NULL),
    ('group','generation',NULL,NULL,NULL),
    ('group','group',NULL,NULL,NULL),
    ('group','guild',NULL,NULL,NULL),
    ('group','horde',NULL,NULL,NULL),
    ('group','household',NULL,NULL,NULL),
    ('group','legion',NULL,NULL,NULL),
    ('group','mob',NULL,NULL,NULL),
    ('group','orchestra',NULL,NULL,NULL),
    ('group','organization',NULL,NULL,NULL),
    ('group','pair',NULL,NULL,NULL),
    ('group','plane full',NULL,NULL,'modern'),
    ('group','plethora',NULL,NULL,NULL),
    ('group','quartet',NULL,NULL,NULL),
    ('group','squad',NULL,NULL,NULL),
    ('group','swarm',NULL,NULL,NULL),
    ('group','team',NULL,NULL,NULL),
    ('group','train full',NULL,NULL,'modern'),
    ('group','trio',NULL,NULL,NULL),
    ('group','troupe',NULL,NULL,NULL),
    ('group','truck full',NULL,NULL,'modern'),
    ('group','union',NULL,NULL,NULL),
    ('group','van full',NULL,NULL,'modern'),
    ('location','a delusion',NULL,NULL,NULL),
    ('location','a dream',NULL,NULL,NULL),
    ('location','a magical realm',NULL,NULL,'fantasy'),
    ('location','Afghanistan',NULL,NULL,NULL),
    ('location','Africa',NULL,NULL,NULL),
    ('location','Algeria',NULL,NULL,NULL),
    ('location','Amsterdam',NULL,NULL,NULL),
    ('location','Anatolia',NULL,NULL,'historic'),
    ('location','ancient times',NULL,NULL,'historic'),
    ('location','Andorra',NULL,NULL,NULL),
    ('location','Angkor Wat',NULL,NULL,NULL),
    ('location','another dimension',NULL,NULL,'scifi'),
    ('location','another galaxy',NULL,NULL,'scifi'),
    ('location','another universe',NULL,NULL,'scifi'),
    ('location','Antarctica',NULL,NULL,NULL),
    ('location','Arabia',NULL,NULL,NULL),
    ('location','Argentina',NULL,NULL,NULL),
    ('location','Asia',NULL,NULL,NULL),
    ('location','Athens',NULL,NULL,NULL),
    ('location','Atlantis',NULL,NULL,'fantasy'),
    ('location','Australia',NULL,NULL,NULL),
    ('location','Austria',NULL,NULL,NULL),
    ('location','Barcelona',NULL,NULL,NULL),
    ('location','Beijing',NULL,NULL,NULL),
    ('location','Belarus',NULL,NULL,NULL),
    ('location','Belgium',NULL,NULL,NULL),
    ('location','Bengladesh',NULL,NULL,NULL),
    ('location','Berlin',NULL,NULL,NULL),
    ('location','Bermuda',NULL,NULL,NULL),
    ('location','Bosnia',NULL,NULL,NULL),
    ('location','Botswana',NULL,NULL,NULL),
    ('location','bottom of the ocean',NULL,'at','scifi'),
    ('location','Brazil',NULL,NULL,NULL),
    ('location','Buenos Aires',NULL,NULL,NULL),
    ('location','Cairo',NULL,NULL,NULL),
    ('location','Cambodia',NULL,NULL,NULL),
    ('location','Canada',NULL,NULL,NULL),
    ('location','Carthage',NULL,NULL,'historic'),
    ('location','Chicago',NULL,NULL,NULL),
    ('location','Chile',NULL,NULL,NULL),
    ('location','China',NULL,NULL,NULL),
    ('location','Colombia',NULL,NULL,NULL),
    ('location','Croatia',NULL,NULL,NULL),
    ('location','Cuba',NULL,NULL,NULL),
    ('location','Curacao',NULL,NULL,NULL),
    ('location','cyberspace',NULL,NULL,'scifi'),
    ('location','Czekia',NULL,NULL,NULL),
    ('location','Dallas',NULL,NULL,NULL),
    ('location','Darfur',NULL,NULL,NULL),
    ('location','deep space',NULL,NULL,'scifi'),
    ('location','Denmark',NULL,NULL,NULL),
    ('location','Detroit',NULL,NULL,NULL),
    ('location','Djibouti',NULL,NULL,NULL),
    ('location','Dubai',NULL,NULL,NULL),
    ('location','Dublin',NULL,NULL,NULL),
    ('location','Earth',NULL,'on','scifi'),
    ('location','Ecuador',NULL,NULL,NULL),
    ('location','Egypt',NULL,NULL,NULL),
    ('location','El Salvador',NULL,NULL,NULL),
    ('location','England',NULL,NULL,NULL),
    ('location','Estonia',NULL,NULL,NULL),
    ('location','Ethiopia',NULL,NULL,NULL),
    ('location','Europe',NULL,NULL,NULL),
    ('location','Finland',NULL,NULL,NULL),
    ('location','France',NULL,NULL,NULL),
    ('location','Gary, Indiana',NULL,NULL,NULL),
    ('location','Geneva',NULL,NULL,NULL),
    ('location','Germany',NULL,NULL,NULL),
    ('location','Giza',NULL,NULL,NULL),
    ('location','Greece',NULL,NULL,NULL),
    ('location','Greenland',NULL,NULL,NULL),
    ('location','Guatamala',NULL,NULL,NULL),
    ('location','Havanna',NULL,NULL,NULL),
    ('location','Heaven',NULL,NULL,'fantasy'),
    ('location','Hell',NULL,NULL,'fantasy'),
    ('location','Hong Kong',NULL,NULL,NULL),
    ('location','Houston',NULL,NULL,NULL),
    ('location','Hungary',NULL,NULL,NULL),
    ('location','hyperspace',NULL,NULL,'scifi'),
    ('location','Iberia',NULL,NULL,NULL),
    ('location','Iceland',NULL,NULL,NULL),
    ('location','India',NULL,NULL,NULL),
    ('location','Indonesia',NULL,NULL,NULL),
    ('location','intergalactic space',NULL,NULL,'scifi'),
    ('location','interplanetary space',NULL,NULL,'scifi'),
    ('location','interstellar space',NULL,NULL,'scifi'),
    ('location','Iran',NULL,NULL,NULL),
    ('location','Iraq',NULL,NULL,NULL),
    ('location','Ireland',NULL,NULL,NULL),
    ('location','Israel',NULL,NULL,NULL),
    ('location','Italy',NULL,NULL,NULL),
    ('location','Jakarta',NULL,NULL,NULL),
    ('location','Japan',NULL,NULL,NULL),
    ('location','Jerusalem',NULL,NULL,NULL),
    ('location','Johannesburg',NULL,NULL,NULL),
    ('location','Jordan',NULL,NULL,NULL),
    ('location','Jupiter',NULL,'on','scifi'),
    ('location','Kazakhstan',NULL,NULL,NULL),
    ('location','Korea',NULL,NULL,NULL),
    ('location','Kuwait',NULL,NULL,NULL),
    ('location','Kyoto',NULL,NULL,NULL),
    ('location','Kyrgyzstan',NULL,NULL,NULL),
    ('location','Laos',NULL,NULL,NULL),
    ('location','Las Vegas',NULL,NULL,NULL),
    ('location','Latvia',NULL,NULL,NULL),
    ('location','Liberia',NULL,NULL,NULL),
    ('location','Libya',NULL,NULL,NULL),
    ('location','Lithuania',NULL,NULL,NULL),
    ('location','London',NULL,NULL,NULL),
    ('location','Los Angeles',NULL,NULL,NULL),
    ('location','Luxembourg',NULL,NULL,NULL),
    ('location','Madagascar',NULL,NULL,NULL),
    ('location','Malaysia',NULL,NULL,NULL),
    ('location','Mali',NULL,NULL,NULL),
    ('location','Malta',NULL,NULL,NULL),
    ('location','Mars',NULL,'on','scifi'),
    ('location','Mecca',NULL,NULL,NULL),
    ('location','Mercury',NULL,'on','scifi'),
    ('location','Mexico',NULL,NULL,NULL),
    ('location','Mexico City',NULL,NULL,NULL),
    ('location','Milwaukee',NULL,NULL,NULL),
    ('location','Minneapolis',NULL,NULL,NULL),
    ('location','Monaco',NULL,NULL,NULL),
    ('location','Mongolia',NULL,NULL,NULL),
    ('location','Morocco',NULL,NULL,NULL),
    ('location','Moscow',NULL,NULL,NULL),
    ('location','Mumbai',NULL,NULL,NULL),
    ('location','Naples',NULL,NULL,NULL),
    ('location','Nepal',NULL,NULL,NULL),
    ('location','Neptune',NULL,'on','scifi'),
    ('location','New Delhi',NULL,NULL,NULL),
    ('location','New York',NULL,NULL,NULL),
    ('location','New Zealand',NULL,NULL,NULL),
    ('location','Nigeria',NULL,NULL,NULL),
    ('location','North America',NULL,NULL,NULL),
    ('location','North Korea',NULL,NULL,NULL),
    ('location','Norway',NULL,NULL,NULL),
    ('location','Okinawa',NULL,NULL,NULL),
    ('location','Oman',NULL,NULL,NULL),
    ('location','Osaka',NULL,NULL,NULL),
    ('location','Oslo',NULL,NULL,NULL),
    ('location','Pakistan',NULL,NULL,NULL),
    ('location','Palestine',NULL,NULL,NULL),
    ('location','Panama',NULL,NULL,NULL),
    ('location','Pangea',NULL,NULL,'fantasy'),
    ('location','Papua New Guinea',NULL,NULL,NULL),
    ('location','Paraguay',NULL,NULL,NULL),
    ('location','parallel universe',NULL,NULL,'scifi'),
    ('location','Paris',NULL,NULL,NULL),
    ('location','parrallel dimenson',NULL,NULL,'scifi'),
    ('location','Pluto',NULL,'on','scifi'),
    ('location','Poland',NULL,NULL,NULL),
    ('location','Portugal',NULL,NULL,NULL),
    ('location','Prague',NULL,NULL,NULL),
    ('location','Rio de Janiero',NULL,NULL,NULL),
    ('location','Romania',NULL,NULL,NULL),
    ('location','Rome',NULL,NULL,NULL),
    ('location','Russia',NULL,NULL,NULL),
    ('location','Rwanda',NULL,NULL,NULL),
    ('location','San Fransisco',NULL,NULL,NULL),
    ('location','Sardinia',NULL,NULL,NULL),
    ('location','Saturn',NULL,'on','scifi'),
    ('location','Saudi Arabia',NULL,NULL,NULL),
    ('location','Scotland',NULL,NULL,NULL),
    ('location','Seattle',NULL,NULL,NULL),
    ('location','Shanghai',NULL,NULL,NULL),
    ('location','Siberia',NULL,NULL,NULL),
    ('location','Sicily',NULL,NULL,NULL),
    ('location','Sierra Leone',NULL,NULL,NULL),
    ('location','Singapore',NULL,NULL,NULL),
    ('location','Slovakia',NULL,NULL,NULL),
    ('location','Somalia',NULL,NULL,NULL),
    ('location','South Africa',NULL,NULL,NULL),
    ('location','South America',NULL,NULL,NULL),
    ('location','South Korea',NULL,NULL,NULL),
    ('location','space',NULL,NULL,'scifi'),
    ('location','Spain',NULL,NULL,NULL),
    ('location','Sri Lanka',NULL,NULL,NULL),
    ('location','Sumeria',NULL,NULL,'historic'),
    ('location','Sweden',NULL,NULL,NULL),
    ('location','Switzerland',NULL,NULL,NULL),
    ('location','Sydney',NULL,NULL,NULL),
    ('location','Syracuse',NULL,NULL,NULL),
    ('location','Tasmania',NULL,NULL,NULL),
    ('location','the Alamo',NULL,'at','historic'),
    ('location','the Alps',NULL,NULL,NULL),
    ('location','the Andes',NULL,NULL,NULL),
    ('location','the Arctic',NULL,NULL,NULL),
    ('location','the Aztec Empire',NULL,NULL,'historic'),
    ('location','the Bahamas',NULL,NULL,NULL),
    ('location','the bayou',NULL,NULL,NULL),
    ('location','the Carribean',NULL,NULL,NULL),
    ('location','the Congo',NULL,NULL,NULL),
    ('location','the Galapagos',NULL,NULL,NULL),
    ('location','the Great Lakes',NULL,NULL,NULL),
    ('location','the Great Lakes area',NULL,NULL,NULL),
    ('location','the Himalayas',NULL,NULL,NULL),
    ('location','the Incan Empire',NULL,NULL,'historic'),
    ('location','the Mediterranean',NULL,NULL,NULL),
    ('location','the mind',NULL,NULL,NULL),
    ('location','the Netherlands',NULL,NULL,NULL),
    ('location','the ocean',NULL,NULL,NULL),
    ('location','the Outback',NULL,NULL,NULL),
    ('location','the Palace of Versailles',NULL,NULL,'historic'),
    ('location','the Panama Canal',NULL,NULL,NULL),
    ('location','the Persian Empire',NULL,NULL,'historic'),
    ('location','the Rockies',NULL,NULL,NULL),
    ('location','the Roman Empire',NULL,NULL,'historic'),
    ('location','the Roman Republic',NULL,NULL,'historic'),
    ('location','the Sahara',NULL,NULL,NULL),
    ('location','the savannah',NULL,NULL,NULL),
    ('location','the sea',NULL,NULL,NULL),
    ('location','the Serengeti',NULL,NULL,NULL),
    ('location','the sky',NULL,'in',NULL),
    ('location','the Soviet Union',NULL,NULL,'modern'),
    ('location','the Suez Canal',NULL,NULL,NULL),
    ('location','the Sun','on',NULL,'scifi'),
    ('location','the Tibetean plateau',NULL,NULL,NULL),
    ('location','the United States',NULL,NULL,NULL),
    ('location','the Vatican',NULL,NULL,'historic'),
    ('location','Tibet',NULL,NULL,NULL),
    ('location','Tobago',NULL,NULL,NULL),
    ('location','Togo',NULL,NULL,NULL),
    ('location','Tokyo',NULL,NULL,NULL),
    ('location','Toronto',NULL,NULL,NULL),
    ('location','Trinidad',NULL,NULL,NULL),
    ('location','Tunisia',NULL,NULL,NULL),
    ('location','Turkey',NULL,NULL,NULL),
    ('location','Turkmenistan',NULL,NULL,NULL),
    ('location','Uganda',NULL,NULL,NULL),
    ('location','Uraguay',NULL,NULL,NULL),
    ('location','Uranus','on',NULL,'scifi'),
    ('location','Valencia',NULL,NULL,NULL),
    ('location','Vancouver',NULL,NULL,NULL),
    ('location','Venus','on',NULL,'scifi'),
    ('location','Venuzuela',NULL,NULL,NULL),
    ('location','Vienna',NULL,NULL,NULL),
    ('location','Vietnam',NULL,NULL,NULL),
    ('location','Wales',NULL,NULL,NULL),
    ('location','Washington',NULL,NULL,NULL),
    ('location','Yemen',NULL,NULL,NULL),
    ('location','Zaire',NULL,NULL,NULL),
    ('location','Zimbabwe',NULL,NULL,NULL),
    ('object','air conditioner','air conditioners',NULL,'modern'),
    ('object','apparatus','apparatuses',NULL,NULL),
    ('object','apple','apples',NULL,NULL),
    ('object','asteroid','asteroids',NULL,'scifi'),
    ('object','ballista','ballistae',NULL,'historic'),
    ('object','ballot','ballots',NULL,NULL),
    ('object','banana','bananas',NULL,NULL),
    ('object','bar of soap','bars of soap',NULL,NULL),
    ('object','battering ram','battering rams',NULL,'historic'),
    ('object','bean','beans',NULL,NULL),
    ('object','bed','beds',NULL,NULL),
    ('object','biscuit','biscuits',NULL,NULL),
    ('object','bone','bones',NULL,NULL),
    ('object','book','books',NULL,NULL),
    ('object','bottle','bottles',NULL,NULL),
    ('object','bouquet','bouquets',NULL,NULL),
    ('object','bow and arrow','bows and arrows',NULL,'historic'),
    ('object','bowl','bowls',NULL,NULL),
    ('object','cactus','cacti',NULL,NULL),
    ('object','cake','cakes',NULL,NULL),
    ('object','camera','cameras',NULL,'modern'),
    ('object','candelabra','candelabras',NULL,NULL),
    ('object','candle','candles',NULL,NULL),
    ('object','candy bar','candy bars',NULL,'modern'),
    ('object','cane','canes',NULL,NULL),
    ('object','cannon','cannons',NULL,'historic'),
    ('object','carrot','carrots',NULL,NULL),
    ('object','catapult','catapults',NULL,'historic'),
    ('object','cauldron','cauldrons',NULL,'fantasy'),
    ('object','cell phone','cell phones',NULL,'modern'),
    ('object','chair','chairs',NULL,NULL),
    ('object','chamber pot','chamber pots',NULL,'historic'),
    ('object','cheese','cheeses',NULL,NULL),
    ('object','cheeseburger','cheeseburgers',NULL,'modern'),
    ('object','cheesesteak','cheesesteaks',NULL,'modern'),
    ('object','chess set','chess sets',NULL,NULL),
    ('object','chisel','chisels',NULL,NULL),
    ('object','cigar','cigars',NULL,'modern'),
    ('object','comet','comets',NULL,'scifi'),
    ('object','computer','computers',NULL,'modern'),
    ('object','cookie','cookies',NULL,NULL),
    ('object','couch','couches',NULL,NULL),
    ('object','crossbow','crossbows',NULL,'historic'),
    ('object','crown','crowns',NULL,'historic'),
    ('object','crystal','crystals',NULL,'fantasy'),
    ('object','cube','cubes',NULL,NULL),
    ('object','cucumber','cucumbers',NULL,NULL),
    ('object','cup','cups',NULL,NULL),
    ('object','dagger','daggers',NULL,'historic'),
    ('object','deck of cards','decks of cards',NULL,NULL),
    ('object','device','devices',NULL,NULL),
    ('object','diamond','diamonds',NULL,NULL),
    ('object','diaper','diapers',NULL,'modern'),
    ('object','dress','dresses',NULL,NULL),
    ('object','drone','drones',NULL,'modern'),
    ('object','drum','drums',NULL,NULL),
    ('object','egg','eggs',NULL,NULL),
    ('object','emerald','emeralds',NULL,NULL),
    ('object','energy drink','energy drinks',NULL,'modern'),
    ('object','farming implement','farming implements',NULL,NULL),
    ('object','flag','flags',NULL,NULL),
    ('object','flashlight','flashlights',NULL,'modern'),
    ('object','flower','flowers',NULL,NULL),
    ('object','frisbee','frisbees',NULL,'modern'),
    ('object','gemstone','gemstones',NULL,NULL),
    ('object','gladius','gladiuses',NULL,'historic'),
    ('object','gourd','gourds',NULL,NULL),
    ('object','guitar','guitars',NULL,'modern'),
    ('object','gun','guns',NULL,NULL),
    ('object','halberd','halberds',NULL,'historic'),
    ('object','ham','hams',NULL,NULL),
    ('object','hamburger','hamburgers',NULL,'modern'),
    ('object','hammer','hammers',NULL,NULL),
    ('object','harpoon','harpoons',NULL,NULL),
    ('object','hat','hats',NULL,NULL),
    ('object','hot dog','hot dogs',NULL,'modern'),
    ('object','jewel','jewels',NULL,NULL),
    ('object','katana','katanas',NULL,'historic'),
    ('object','key','keys',NULL,NULL),
    ('object','knife','knives',NULL,NULL),
    ('object','lamp','lamps',NULL,'modern'),
    ('object','laser gun','laser guns',NULL,'scifi'),
    ('object','letter','letters',NULL,NULL),
    ('object','loaf of bread','loaves of bread',NULL,NULL),
    ('object','machine','machines',NULL,NULL),
    ('object','magazine','magazines',NULL,'modern'),
    ('object','magnet','magnets',NULL,'modern'),
    ('object','map','maps',NULL,NULL),
    ('object','meatloaf','meatloaves',NULL,NULL),
    ('object','mechanism','mechanisms',NULL,NULL),
    ('object','meteor','meteors',NULL,'scifi'),
    ('object','MRE','MREs',NULL,'modern'),
    ('object','mummy','mummies',NULL,'historic'),
    ('object','mushroom','mushrooms',NULL,NULL),
    ('object','musical instrument','musical instruments',NULL,NULL),
    ('object','necklace','necklace',NULL,NULL),
    ('object','orange','oranges',NULL,NULL),
    ('object','oxygen tank','oxygen tanks',NULL,'modern'),
    ('object','paintbrush','paintbrushes',NULL,NULL),
    ('object','painting','paintings',NULL,NULL),
    ('object','pair of boots','pairs of boots',NULL,NULL),
    ('object','pair of glasses','pairs of glasses',NULL,'modern'),
    ('object','pair of gloves','pairs of gloves',NULL,NULL),
    ('object','pair of goggles','pairs of goggles',NULL,'modern'),
    ('object','pair of mittens','pairs of mittens',NULL,NULL),
    ('object','pair of pants','pairs of pants',NULL,NULL),
    ('object','pair of shoes','pairs of shoes',NULL,NULL),
    ('object','pepper','peppers',NULL,NULL),
    ('object','piano','pianos',NULL,'modern'),
    ('object','pickle','pickles',NULL,NULL),
    ('object','pie','pies',NULL,NULL),
    ('object','pike','pikes',NULL,'historic'),
    ('object','pistol','pistols',NULL,NULL),
    ('object','plant','plants',NULL,NULL),
    ('object','pocket watch','picket watches',NULL,'historic'),
    ('object','pot','pots',NULL,NULL),
    ('object','potion','potions',NULL,'fantasy'),
    ('object','pumpkin','pumpkins',NULL,NULL),
    ('object','puppet','puppets',NULL,NULL),
    ('object','rifle','rifles',NULL,NULL),
    ('object','rock','rocks',NULL,NULL),
    ('object','ruby','rubies',NULL,NULL),
    ('object','rutebaga','rutebagas',NULL,NULL),
    ('object','sapphire','sapphires',NULL,NULL),
    ('object','sausage','sausages',NULL,NULL),
    ('object','scarf','scarves',NULL,NULL),
    ('object','scroll','scrolls',NULL,'historic'),
    ('object','shield','shields',NULL,'historic'),
    ('object','shirt','shirts',NULL,NULL),
    ('object','smart phone','smart phones',NULL,'modern'),
    ('object','soda','sodas',NULL,'modern'),
    ('object','soup','soup',NULL,NULL),
    ('object','spacesuit','spacesuit',NULL,'modern'),
    ('object','spear','spears',NULL,'historic'),
    ('object','staff','staves',NULL,'fantasy'),
    ('object','statue','statues',NULL,NULL),
    ('object','steak','steaks',NULL,NULL),
    ('object','suit','suits',NULL,'modern'),
    ('object','sweater','sweaters',NULL,NULL),
    ('object','sword','swords',NULL,'historic'),
    ('object','table','tables',NULL,NULL),
    ('object','tablet','tablets',NULL,'historic'),
    ('object','telephone','telephones',NULL,'modern'),
    ('object','ticket','tickets',NULL,NULL),
    ('object','time machine','time machines',NULL,'scifi'),
    ('object','toiler plunger','toilet plungers',NULL,'modern'),
    ('object','toilet','toilets',NULL,NULL),
    ('object','tome','tomes',NULL,'fantasy'),
    ('object','tool','tools',NULL,NULL),
    ('object','tooth','teeth',NULL,NULL),
    ('object','top hat','top hats',NULL,'modern'),
    ('object','torch','torches',NULL,'historic'),
    ('object','treasure map','treasure maps',NULL,'historic'),
    ('object','trebuchet','trebuchets',NULL,'historic'),
    ('object','tree','trees',NULL,NULL),
    ('object','tuxedo','tuxedos',NULL,'modern'),
    ('object','TV','TVs',NULL,'modern'),
    ('object','vase','vases',NULL,NULL),
    ('object','wand','wands',NULL,'fantasy'),
    ('object','weapon','weapons',NULL,NULL),
    ('object','wristwatch','wristwatches',NULL,'modern'),
    ('object','xylophone','xylophones',NULL,NULL),
    ('period','a blizzard',NULL,NULL,NULL),
    ('period','a drought',NULL,NULL,NULL),
    ('period','a flood',NULL,NULL,NULL),
    ('period','a fundraiser',NULL,NULL,NULL),
    ('period','a hurricane',NULL,NULL,NULL),
    ('period','a leap year',NULL,NULL,NULL),
    ('period','a pilgramage',NULL,NULL,NULL),
    ('period','a revolution',NULL,NULL,NULL),
    ('period','a snowstorm',NULL,NULL,NULL),
    ('period','a storm',NULL,NULL,NULL),
    ('period','a sunset',NULL,NULL,NULL),
    ('period','a thunderstorm',NULL,NULL,NULL),
    ('period','a vacation',NULL,NULL,NULL),
    ('period','a war',NULL,NULL,NULL),
    ('period','an election',NULL,NULL,NULL),
    ('period','another time',NULL,NULL,NULL),
    ('period','April',NULL,NULL,NULL),
    ('period','archaic times',NULL,NULL,'historic'),
    ('period','August',NULL,NULL,NULL),
    ('period','autumn',NULL,NULL,NULL),
    ('period','battle',NULL,NULL,NULL),
    ('period','Christmas',NULL,NULL,NULL),
    ('period','December',NULL,NULL,NULL),
    ('period','early dawn',NULL,NULL,NULL),
    ('period','February',NULL,NULL,NULL),
    ('period','Hanukkah',NULL,NULL,NULL),
    ('period','January',NULL,NULL,NULL),
    ('period','July',NULL,NULL,NULL),
    ('period','June',NULL,NULL,NULL),
    ('period','Lent',NULL,NULL,NULL),
    ('period','March',NULL,NULL,NULL),
    ('period','May',NULL,NULL,NULL),
    ('period','medieval times',NULL,NULL,'historic'),
    ('period','modern times',NULL,NULL,'modern'),
    ('period','November',NULL,NULL,NULL),
    ('period','October',NULL,NULL,NULL),
    ('period','Passover',NULL,NULL,NULL),
    ('period','Ramadan',NULL,NULL,NULL),
    ('period','Roman times',NULL,NULL,'historic'),
    ('period','September',NULL,NULL,NULL),
    ('period','spring',NULL,NULL,NULL),
    ('period','summer',NULL,NULL,NULL),
    ('period','Thanksgiving',NULL,NULL,NULL),
    ('period','the afternoon',NULL,NULL,NULL),
    ('period','the American Civil War',NULL,NULL,'historic'),
    ('period','the apocalypse',NULL,NULL,NULL),
    ('period','the bronze age',NULL,NULL,'historic'),
    ('period','the Classical era',NULL,NULL,'historic'),
    ('period','the Cold War',NULL,NULL,'modern'),
    ('period','the colonial era',NULL,NULL,'historic'),
    ('period','the dark ages',NULL,NULL,'historic'),
    ('period','the day',NULL,NULL,NULL),
    ('period','the distant future',NULL,NULL,NULL),
    ('period','the distant past',NULL,NULL,'historic'),
    ('period','the Dreamtime',NULL,NULL,'fantasy'),
    ('period','the evening',NULL,NULL,NULL),
    ('period','the fall',NULL,NULL,NULL),
    ('period','the future',NULL,NULL,NULL),
    ('period','the Ice Age',NULL,NULL,'historic'),
    ('period','the information age',NULL,NULL,'modern'),
    ('period','the monsoon',NULL,NULL,NULL),
    ('period','the morning',NULL,NULL,NULL),
    ('period','the night',NULL,NULL,NULL),
    ('period','the past',NULL,NULL,NULL),
    ('period','the Spanish Civil War',NULL,NULL,'historic'),
    ('period','the stone age',NULL,NULL,'historic'),
    ('period','the sunrise',NULL,NULL,NULL),
    ('period','the weekend',NULL,NULL,'modern'),
    ('period','the work week',NULL,NULL,'modern'),
    ('period','winter',NULL,NULL,NULL),
    ('period','World War I',NULL,NULL,'modern'),
    ('period','World War II',NULL,NULL,'modern'),
    ('setting','academy','acadamies','at',NULL),
    ('setting','airplane','airplanes','on','modern'),
    ('setting','airplane','airplanes','on','modern'),
    ('setting','airport','airports','at','modern'),
    ('setting','airship','airships','on','scifi'),
    ('setting','amusement park','amusement parks','at',NULL),
    ('setting','aqueduct','aqueducts','on','historic'),
    ('setting','arcade','arcades','at','modern'),
    ('setting','archipelago','archipelagos','on',NULL),
    ('setting','area','areas',NULL,NULL),
    ('setting','arena','arenas',NULL,NULL),
    ('setting','asteroid','asteroids','on','scifi'),
    ('setting','avenue','avenues','on',NULL),
    ('setting','backyard','backyards',NULL,NULL),
    ('setting','bar','bars','at',NULL),
    ('setting','basement','basements',NULL,NULL),
    ('setting','battleship','battleships','on',NULL),
    ('setting','beach','beaches','on',NULL),
    ('setting','blimp','blimps','on','modern'),
    ('setting','boardwalk','boardwalks','on','modern'),
    ('setting','boat','boats','on',NULL),
    ('setting','bowling alley','bowling alleys','at','modern'),
    ('setting','bridge','bridges','on',NULL),
    ('setting','bunker','bunkers',NULL,'modern'),
    ('setting','bus','buses','on','modern'),
    ('setting','campsite','campsites','at',NULL),
    ('setting','cargo ship','cargo ships','on',NULL),
    ('setting','casino','casinos','at','modern'),
    ('setting','castle','castles',NULL,NULL),
    ('setting','cathedral','cathedrals',NULL,NULL),
    ('setting','cave','caves',NULL,NULL),
    ('setting','cavern','caverns',NULL,NULL),
    ('setting','church','churches',NULL,NULL),
    ('setting','circus','circuses','at',NULL),
    ('setting','city','cities',NULL,NULL),
    ('setting','coastline','coastlines','on',NULL),
    ('setting','coffee shop','coffee shops','at','modern'),
    ('setting','concert','concerts','at',NULL),
    ('setting','courthouse','courthouses','at','modern'),
    ('setting','cruise ship','cruise ships','on','modern'),
    ('setting','crypt','crypts',NULL,NULL),
    ('setting','dance club','dance clubs','at','modern'),
    ('setting','desert','deserts',NULL,NULL),
    ('setting','diner','diners','at','modern'),
    ('setting','discotheque','discotheques','at','modern'),
    ('setting','dockyard','dockyards','at',NULL),
    ('setting','dungeon','dungeons',NULL,'historic'),
    ('setting','empire','empire',NULL,'historic'),
    ('setting','event horizon','event horizons','at','scifi'),
    ('setting','factory','factory',NULL,'modern'),
    ('setting','farm','farms','on',NULL),
    ('setting','festival','festivals','at',NULL),
    ('setting','field','fields',NULL,NULL),
    ('setting','forest','forests',NULL,NULL),
    ('setting','fortress','fortresses',NULL,NULL),
    ('setting','foxhole','forxholes',NULL,'modern'),
    ('setting','galleon','galleons','on','historic'),
    ('setting','gambling den','gambling dens',NULL,NULL),
    ('setting','game show','game shows','on','modern'),
    ('setting','garden','gardens',NULL,NULL),
    ('setting','graveyard','graveyards',NULL,NULL),
    ('setting','grove','groves',NULL,NULL),
    ('setting','gym','gyms','at',NULL),
    ('setting','highway','highways','on',NULL),
    ('setting','hospital','hospitals','at',NULL),
    ('setting','hostel','hostels','at','modern'),
    ('setting','hotel','hotels','at','modern'),
    ('setting','house','houses','at',NULL),
    ('setting','iceberg','icebergs','on',NULL),
    ('setting','inn','inns','at',NULL),
    ('setting','island','islands','on',NULL),
    ('setting','jungle','jungles',NULL,NULL),
    ('setting','kingdom','kingdoms',NULL,'historic'),
    ('setting','kitchen','kitchens',NULL,NULL),
    ('setting','laboratory','laboratories',NULL,NULL),
    ('setting','lake','lake','on',NULL),
    ('setting','land','lands',NULL,NULL),
    ('setting','leper colony',NULL,NULL,NULL),
    ('setting','library','libraries','at',NULL),
    ('setting','lodge','lodges','at',NULL),
    ('setting','mansion','mansions','at',NULL),
    ('setting','marina','marinas','at',NULL),
    ('setting','military base','military bases','on',NULL),
    ('setting','mine','mines',NULL,NULL),
    ('setting','moon','moons','on','scifi'),
    ('setting','mosque','mosques',NULL,NULL),
    ('setting','mountain','mountains','on',NULL),
    ('setting','museum','museums',NULL,NULL),
    ('setting','nation',NULL,NULL,'modern'),
    ('setting','ocean','oceans',NULL,NULL),
    ('setting','oil rig','oil rigs','on','modern'),
    ('setting','orbital platform','orbital platforms','on','scifi'),
    ('setting','palace','palaces',NULL,'historic'),
    ('setting','park','parks','at',NULL),
    ('setting','party','parties','at',NULL),
    ('setting','pit','pits',NULL,NULL),
    ('setting','place','places','at',NULL),
    ('setting','plain','plains','on',NULL),
    ('setting','planet','planets','on','scifi'),
    ('setting','pontoon','pontoon','on','modern'),
    ('setting','prison','prisons',NULL,'modern'),
    ('setting','pyramid','pyramids',NULL,NULL),
    ('setting','quarry','quarries',NULL,NULL),
    ('setting','racetrack','racetracks','on',NULL),
    ('setting','radio transmission','radio transmissions','over','modern'),
    ('setting','rainforest','rainforests',NULL,NULL),
    ('setting','rave','raves','at','modern'),
    ('setting','realm','realms',NULL,'historic'),
    ('setting','research station','research stations','at',NULL),
    ('setting','restaurant','restaurants','at',NULL),
    ('setting','river','rivers','on',NULL),
    ('setting','road','roads','on',NULL),
    ('setting','school','schools','at',NULL),
    ('setting','sea','seas',NULL,NULL),
    ('setting','sewer system','sewer systems',NULL,NULL),
    ('setting','shipyard','shipyards','at','modern'),
    ('setting','situation','situations',NULL,NULL),
    ('setting','space freighter','space frieghters','on','scifi'),
    ('setting','spaceport','spaceports',NULL,'scifi'),
    ('setting','stadium','stadiums',NULL,NULL),
    ('setting','star','stars','around','scifi'),
    ('setting','street','streets','on',NULL),
    ('setting','submarine','submarines','on','modern'),
    ('setting','subway system','subway systems',NULL,'modern'),
    ('setting','supermarket','supermarkets',NULL,'modern'),
    ('setting','talk show','talk shows','on','modern'),
    ('setting','tavern','taverns',NULL,'historic'),
    ('setting','teahouse','teahouses',NULL,NULL),
    ('setting','temple','temples',NULL,NULL),
    ('setting','theatre','theatres','at','modern'),
    ('setting','tomb','tombs',NULL,NULL),
    ('setting','tower','towers',NULL,'historic'),
    ('setting','town','towns',NULL,NULL),
    ('setting','train','trains','on','modern'),
    ('setting','trainyard','trainyards','at','modern'),
    ('setting','trench','trenches',NULL,'modern'),
    ('setting','tundra','tundras',NULL,NULL),
    ('setting','tunnel','tunnels',NULL,NULL),
    ('setting','valley','valleys',NULL,NULL),
    ('setting','vault','vaults',NULL,NULL),
    ('setting','village','villages',NULL,NULL),
    ('setting','volcano','volcanos','inside',NULL),
    ('setting','warehouse','warehouses',NULL,NULL),
    ('setting','wasteland','wastelands',NULL,NULL),
    ('setting','world','worlds',NULL,'fantasy'),
    ('setting','yacht','yachts','on','modern'),
    ('setting','zeppelin','zeppelin','on','modern'),
    ('setting','zoo','zoos','at',NULL),
    ('substance','air',NULL,NULL,'fantasy'),
    ('substance','amber',NULL,NULL,NULL),
    ('substance','antimatter',NULL,NULL,'scifi'),
    ('substance','bacteria',NULL,NULL,'scifi'),
    ('substance','bamboo',NULL,NULL,NULL),
    ('substance','blood',NULL,NULL,'fantasy'),
    ('substance','bone',NULL,NULL,NULL),
    ('substance','brass',NULL,NULL,NULL),
    ('substance','brick',NULL,NULL,NULL),
    ('substance','bronze',NULL,NULL,NULL),
    ('substance','candy',NULL,NULL,'modern'),
    ('substance','ceramic',NULL,NULL,NULL),
    ('substance','cheese',NULL,NULL,NULL),
    ('substance','circuitry',NULL,NULL,'scifi'),
    ('substance','circuitry',NULL,NULL,'scifi'),
    ('substance','clay',NULL,NULL,NULL),
    ('substance','concrete',NULL,NULL,'modern'),
    ('substance','copper',NULL,NULL,NULL),
    ('substance','dirt',NULL,NULL,NULL),
    ('substance','driftwood',NULL,NULL,NULL),
    ('substance','dust',NULL,NULL,NULL),
    ('substance','electricity',NULL,NULL,'scifi'),
    ('substance','fabric',NULL,NULL,NULL),
    ('substance','fire',NULL,NULL,NULL),
    ('substance','flesh',NULL,NULL,'fantasy'),
    ('substance','food',NULL,NULL,NULL),
    ('substance','garbage',NULL,NULL,NULL),
    ('substance','glass',NULL,NULL,NULL),
    ('substance','gold',NULL,NULL,NULL),
    ('substance','grass',NULL,NULL,NULL),
    ('substance','hair',NULL,NULL,NULL),
    ('substance','hydrocarbons',NULL,NULL,'modern'),
    ('substance','ice',NULL,NULL,NULL),
    ('substance','iron',NULL,NULL,NULL),
    ('substance','lasers',NULL,NULL,'scifi'),
    ('substance','light',NULL,NULL,NULL),
    ('substance','magic',NULL,NULL,'fantasy'),
    ('substance','marble',NULL,NULL,NULL),
    ('substance','metal',NULL,NULL,NULL),
    ('substance','nanobots',NULL,NULL,'scifi'),
    ('substance','paint',NULL,NULL,NULL),
    ('substance','paper',NULL,NULL,NULL),
    ('substance','petrified wood',NULL,NULL,NULL),
    ('substance','pewter',NULL,NULL,NULL),
    ('substance','plaster',NULL,NULL,NULL),
    ('substance','plastic',NULL,NULL,'modern'),
    ('substance','porcelain',NULL,NULL,NULL),
    ('substance','rubber',NULL,NULL,NULL),
    ('substance','salt',NULL,NULL,NULL),
    ('substance','sand',NULL,NULL,NULL),
    ('substance','silver',NULL,NULL,NULL),
    ('substance','slime',NULL,NULL,'fantasy'),
    ('substance','stone',NULL,NULL,NULL),
    ('substance','straw',NULL,NULL,NULL),
    ('substance','titanium',NULL,NULL,'modern'),
    ('substance','unobtanium',NULL,NULL,'scifi'),
    ('substance','water',NULL,NULL,NULL),
    ('substance','wood',NULL,NULL,NULL),
    ('substance','wool',NULL,NULL,NULL);

